Handle `CatchableError` thrown by current step.
